### PR TITLE
Develop ::: Fixed a few bugs I found

### PR DESCRIPTION
**Pull request by cloudmanic**
I fixed a few bugs I found in the library. Great library! Thanks for writing it.

I am hoping to deploy this library to a number of projects I have right now so if you could update your spark as well that would be amazing. 

Thanks.
~Spicer

### CODE REVIEW

**Comment by joelcox** [comment]
Hi Spicer, thanks for your pull request. I'll look into this later this weekend.

**Comment by joelcox** [comment]
Hi Spicer, I promised to get back to you this weekend, but I had something else coming up. I'll look into this tomorrow. Please make sure you make the pull request on the develop branch and merged all changes (if any).

Thanks!

**Comment by joelcox** [comment]
I merged in your changes and added you to the 'thank you' section. Thanks for helping out!

**Comment by cloudmanic** [comment]
Hey Joel,

Thanks for merging this in. Sorry did not do a pull request to the develop branch. I will do that next time.

~Spicer

**Comment by joelcox** [comment]
No problem, it just means I need to get to my machine instead of merging the changes from my phone/browser. :)

**Pull request closed without merging**
